# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e88747c44d57cff047e4fcce6686b345c82183e073f893417adf2d13c66f15b4ba588955592933129356d99069b1f3af30d0bf3e653b2a8f9018aa3d9e3eb57

test:
  secret_key_base: 4c500385bb9c72b982be50310bf48ced6d2294f5dc4784022df73276141a243cd3c7a358b7586ffc3493436efb86bc0277c7ded3f0b4c27308fd36038bbe151d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
